# Generated by Django 3.2.5 on 2021-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='Firstname')),
                ('lastName', models.CharField(max_length=100, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
